
-- Question 1
select Customer_Name
from S_Customer_t,S_ORDER_t
where s_customer_t.customer_id = S_ORDER_t.customer_id









-- Question 6
SELECT ORDER_ID, S_PRODUCT_T.PRODUCT_ID, STANDARD_PRICE, ORDERED_QUANTITY, STANDARD_PRICE * ORDERED_QUANTITY
FROM S_PRODUCT_T, S_ORDER_LINE_T
WHERE S_PRODUCT_T.PRODUCT_ID = S_ORDER_LINE_T.PRODUCT_ID
ORDER BY ORDER_ID, S_PRODUCT_T.PRODUCT_ID;


-- Question 7
SELECT ORDER_ID, SUM(STANDARD_PRICE * ORDERED_QUANTITY)
FROM S_PRODUCT_T, S_ORDER_LINE_T
WHERE S_PRODUCT_T.PRODUCT_ID = S_ORDER_LINE_T.PRODUCT_ID
GROUP BY ORDER_ID
ORDER BY ORDER_ID;
